// Mock data for testing search functionality
export const mockBooks = [
  {
    id: '1',
    title: 'Learning React: Modern Patterns for Developing React Apps',
    author: 'Alex Banks, Eve Porcello',
    description: 'If you want to learn how to build efficient React applications, this is the book for you. Ideal for web developers and software engineers who understand how JavaScript, CSS, and HTML work in the browser, this updated edition provides best practices and patterns for writing modern React code.',
    slug: 'learning-react',
    price: 250000,
    rating: 4.5,
    category: 'Programming',
    genre: 'Technology',
    quantity: 15,
    sold: 89,
    image: ['/images/learning-react.jpg'],
    isDisable: false,
    attributes: {
      isbn: '978-1492051718',
      publisher: 'O\'Reilly Media',
      publishDate: new Date('2020-06-01'),
      pages: 310,
      language: 'English',
      edition: '2nd Edition',
    },
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2023-01-15'),
  },
  {
    id: '2', 
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: 'Robert C. Martin',
    description: 'Even bad code can function. But if code isn\'t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code.',
    slug: 'clean-code',
    price: 180000,
    rating: 4.8,
    category: 'Programming',
    genre: 'Technology',
    quantity: 8,
    sold: 156,
    image: ['/images/clean-code.jpg'],
    isDisable: false,
    attributes: {
      isbn: '978-0132350884',
      publisher: 'Prentice Hall',
      publishDate: new Date('2008-08-01'),
      pages: 464,
      language: 'English',
      edition: '1st Edition',
    },
    createdAt: new Date('2023-02-10'),
    updatedAt: new Date('2023-02-10'),
  },
  {
    id: '3',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    description: 'Doing well with money isn\'t necessarily about what you know. It\'s about how you behave. And behavior is hard to teach, even to really smart people.',
    slug: 'psychology-of-money',
    price: 120000,
    rating: 4.7,
    category: 'Finance',
    genre: 'Self-Help',
    quantity: 23,
    sold: 342,
    image: ['/images/psychology-money.jpg'],
    isDisable: false,
    attributes: {
      isbn: '978-0857197689',
      publisher: 'Harriman House',
      publishDate: new Date('2020-09-08'),
      pages: 256,
      language: 'English',
      edition: '1st Edition',
    },
    createdAt: new Date('2023-03-05'),
    updatedAt: new Date('2023-03-05'),
  },
  {
    id: '4',
    title: 'Lạc Trôi',
    author: 'Hà Anh Tuấn',
    description: 'Một tập thơ đẹp về tình yêu, về những cảm xúc trong sáng và lãng mạn của tuổi trẻ.',
    slug: 'lac-troi',
    price: 85000,
    rating: 4.2,
    category: 'Literature',
    genre: 'Poetry',
    quantity: 45,
    sold: 78,
    image: ['/images/lac-troi.jpg'],
    isDisable: false,
    attributes: {
      isbn: '978-6041234567',
      publisher: 'NXB Trẻ',
      publishDate: new Date('2022-11-15'),
      pages: 128,
      language: 'Vietnamese',
      edition: '1st Edition',
    },
    createdAt: new Date('2023-04-12'),
    updatedAt: new Date('2023-04-12'),
  }
];

// Mock search suggestions for semantic search
export const searchSuggestions = [
  'sách lập trình Python cho người mới bắt đầu',
  'tiểu thuyết tình cảm hay nhất',
  'sách self-help phát triển bản thân',
  'sách lịch sử Việt Nam', 
  'sách kinh doanh khởi nghiệp',
  'sách thiết kế UI/UX',
  'truyện ngắn văn học Việt Nam',
  'sách nấu ăn món Á',
];